;
; This is a supporting document purely describing the grammar of bconf using ABNF and makes use of case-sensitivity
; support defined in RFC 7405 (https://datatracker.ietf.org/doc/html/rfc7405). Some grammar rules in this document
; refer to characters by their Unicode Code Points in UTF-8 encoding as bconf documents are expected to be encoded
; in UTF-8.
;
; While this document contains more verbose descriptions of the syntax, all implementation logic exists solely in
; the SPEC.md file and should be considered as the source of truth if there are conflicting descriptions between the
; two documents unless stated otherwise.
;

bconf = OWSP [ *comment ] OWSP [ LBRACE ] [ block-body ] [ RBRACE ] OWSP [ *comment ] OWSP

identifier = 1*( %x21 / %x23 / %x25-26 / %x2A-2B / %x2D / %x30-3A / %x41-5A / %x5C / %x5E-5F / %x61-7A / %x7E / %xA1-D7FF / %xE000-10FFFF ) ; No control chars or special characters (", $, ', (, ), comma, ., ;, <, =, >, ?, @, [, ] `, {, |, })
directive-ident = ATSIGN identifier
variable-ident = 1*2DOLLARSIGN identifier

;
; Statements
;
comment = "//" *( HTAB / %x20-7E / %xA0-D7FF / %xE000-10FFFF )  ; Tab + printable chars, no controls
key-value = key-path *WSP ( "=" / "?=" / "<<" ) *WSP value
key-value =/ key-path *WSP block 
spread = 3PERIOD spread-source
spread-source = dynamic-value / array / block;

;
; Keys
;
key = ( identifier / variable-ident )
key =/ DQUOTE 1*string-content DQUOTE
key-path = key *( *index / ( PERIOD key ) )
index = LBRACKET OWSP integer OWSP RBRACKET

;
; Values
;
value = primitive / dynamic-value / object / array
primitive = string / number / boolean / null
dynamic-value = modifier / variable-path / resolver / directive

variable-path = variable-ident *( *index / *( PERIOD key ) )

modifier = identifier LPAREN OWSP [ modifier-item *( OWSP COMMA OWSP modifier-item ) [ OWSP COMMA ] ] OWSP RPAREN 
modifier-item = value / spread

resolver = LPAREN OWSP [ PIPE ] OWSP resolver-branch *( OWSP PIPE OWSP resolver-branch ) OWSP RPAREN 
resolver-branch = [ ( boolean / dynamic-value ) OWSP "=>" OWSP ] value

directive = directive-ident *( WSP ( value / identifier ) )

block = LBRACE OWSP block-body OWSP RBRACE 
block-body = OWSP *statement OWSP 
statement = [ identifier / directive / key-value / spread ] *WSP ( ( SEMICOLON *WSP [ comment ] ) / NEWLINE ) ; identifier refers to boolean shorthand
statement =/ comment NEWLINE

array = LBRACKET OWSP [ array-item *( OWSP COMMA OWSP array-item ) [ OWSP COMMA ] ] OWSP RBRACKET 
array-item = value / spread

string = DQUOTE *string-content DQUOTE
string =/ 3DQUOTE *( string-content / HTAB / NEWLINE ) 3DQUOTE
string-content = string-char / escaped-char / embedded-value

string-char     = %x20-21 / %x23-5B / %x5D-7E / %xA0-D7FF / %xE000-10FFFF ; Printable chars, no control chars, `"` or `\`. Unescaped $ are allowed since embed sequences must have { following it.
embedded-value  = DOLLARSIGN LBRACE OWSP ( primitive / dynamic-value ) OWSP RBRACE
escaped-char    = "\" ( 
    %x22 /          ; "    quotation mark
    %x24 /          ; $    dollar sign 
    %x5C /          ; \    backslash
    %x62 /          ; b    backspace
    %x66 /          ; f    form feed
    %x6E /          ; n    new line
    %x72 /          ; r    carriage return
    %x74 /          ; t    tab
    %x75 4HEXDIG /  ; uXXXX   U+XXXX
    %x55 8HEXDIG    ; UXXXXXXXX  U+XXXXXXXX
)

number         = float / integer
number-prefix  = "-" / "+" 
integer        = [ number-prefix ] dec-int
float          = [ number-prefix ] ( ( dec-int PERIOD dec-int [ exponent ] ) / ( dec-int exponent ) )
dec-int        = DIGIT *( [ "_" ] *DIGIT )
exponent       = "e" integer

boolean = %s"true" / %s"false"
null = %s"null"

;
; BConf Symbols & Whitespace
;
NEWLINE       = LF / CRLF
OWSP          = *( WSP / NEWLINE ) ; Optional white space. Different to WSP, this denotes white space that carries no syntactical significance
LBRACE        = "{"
RBRACE        = "}"
LBRACKET      = "["
RBRACKET      = "]"
LPAREN        = "("
RPAREN        = ")"
COMMA         = ","
SEMICOLON     = ";"
PERIOD        = "."
DOLLARSIGN    = "$"
ATSIGN        = "@"
PIPE          = "|"

;
; Core ABNF Rules (included for clarity)
;
ALPHA   = %x41-5A / %x61-7A     ; A-Z / a-z
CR      = %x0D                  ; carriage return
CRLF    = CR LF                 ; internet standard newline
DIGIT   = %x30-39               ; 0-9
DQUOTE  = %x22                  ; " (double quote)
HEXDIG  = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
HTAB    = %x09                  ; horizontal tab
LF      = %x0A                  ; linefeed
SP      = %x20                  ; space
WSP     = SP / HTAB             ; white space
